SELECT OrderID
	, CustomerID
	, Amount
	, FIRST_VALUE(Amount) OVER(PARTITION BY CustomerID ORDER BY OrderID ASC) AS [FIRST_VALUE]
	, LEAD(Amount) OVER(PARTITION BY CustomerID ORDER BY OrderID ASC) AS [LEAD]
	, LAG(Amount) OVER(PARTITION BY CustomerID ORDER BY OrderID ASC) AS [LAG]
	, LAST_VALUE(Amount) OVER(PARTITION BY CustomerID ORDER BY OrderID ASC) AS [LAST_VALUE]
FROM PurchaseOrder
WHERE OrderID <= 5