SELECT OrderID
	, CustomerID
	, Amount
	, ROW_NUMBER() OVER(PARTITION BY CustomerID ORDER BY OrderID ASC) AS [ROW_NUMBER]
	, RANK() OVER(PARTITION BY CustomerID ORDER BY OrderID ASC) AS [RANK]
	, DENSE_RANK() OVER(PARTITION BY CustomerID ORDER BY OrderID ASC) AS [DENSE_RANK]
FROM PurchaseOrder
WHERE OrderID <= 5