CREATE TABLE #MyTable
(
	[ID] INT NOT NULL IDENTITY(1, 1)
	, [Name] VARCHAR(50)
);

INSERT INTO #MyTable ([Name]) VALUES ('A'), ('B');

SELECT * FROM #MyTable;

SELECT @@IDENTITY;
SELECT IDENT_CURRENT ('#MyTable');
SELECT SCOPE_IDENTITY();