SELECT * FROM Product
FOR XML RAW

SELECT * FROM Product
FOR XML AUTO

SELECT * FROM Product
FOR XML AUTO, ELEMENTS

SELECT * FROM Product
FOR XML PATH

SELECT * FROM Product
FOR XML PATH ('')

SELECT * FROM Product
FOR XML PATH ('Products')